from typing import List, Optional, Protocol
from src.domain.entities.property import PropertyDefinition, PropertyGroup, EntityPropertyLink

class IPropertyRepository(Protocol):
    def list_groups(self, workspace_id: int) -> List[PropertyGroup]:
        ...
    def save_group(self, group: PropertyGroup, workspace_id: int) -> PropertyGroup:
        ...
    
    def list_definitions(self, workspace_id: int) -> List[PropertyDefinition]:
        ...
    def save_definition(self, prop_def: PropertyDefinition, workspace_id: int) -> PropertyDefinition:
        ...
    def get_definition_by_name(self, name: str, workspace_id: int) -> Optional[PropertyDefinition]:
        ...
    
    def list_entity_links(self, entity_type: str, workspace_id: int) -> List[EntityPropertyLink]:
        ...
    def save_entity_link(self, link: EntityPropertyLink, workspace_id: int) -> EntityPropertyLink:
        ...
    def delete_entity_link(self, link_id: int, workspace_id: int) -> bool:
        ...
