from typing import Optional, Protocol, List
from src.domain.entities.user import User

class IUserRepository(Protocol):
    def get_by_email(self, email: str) -> Optional[User]:
        ...
    
    def save(self, user: User) -> User:
        ...
    def list_all(self) -> List[User]:
        ...
    def count(self) -> int:
        ...
